# Generated by Django 3.2.7 on 2021-09-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_order_orderitem_review_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='htttpssdfsdf', upload_to='images'),
            preserve_default=False,
        ),
    ]
